version: "3.9"
volumes:
    prometheus_data: { }

services:

    resource-server:
      build: .
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/exhibitionsdb
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      networks:
        - test-network

    prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus/config/:/etc/prometheus
        - ./prometheus/data/prometheus:/data
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=31d'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - "9090:9090"
      depends_on:
        - resource-server
      networks:
        - test-network

    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      networks:
        - test-network

    zipkin:
      image: openzipkin/zipkin
      environment:
        - STORAGE_TYPE=mem
      ports:
        - "9411:9411"
      depends_on:
        - resource-server
      networks:
        - test-network


networks:
  test-network: